import api from "./index";
import { HomeTask, Appliance } from "../types/home";

// --- Task Functions (CRUD) ---

/**
 * (Read) Fetches all home maintenance tasks.
 */
export const fetchHomeTasks = async (): Promise<HomeTask[]> => {
  const response = await api.get<HomeTask[]>("/home/tasks");
  return response.data;
};

/**
 * (Create) Adds a new home maintenance task.
 * The input type excludes the 'id' because it's generated by the backend.
 */
export const addHomeTask = async (taskData: Omit<HomeTask, 'id'>): Promise<HomeTask> => {
  const response = await api.post<HomeTask>("/home/tasks", taskData);
  return response.data;
};

/**
 * (Update) Updates an existing task (e.g., marking it as complete).
 * It sends the entire updated task object to the backend.
 */
export const updateHomeTask = async (task: HomeTask): Promise<HomeTask> => {
  const response = await api.put<HomeTask>(`/home/tasks/${task.id}`, task);
  return response.data;
};

/**
 * (Delete) Deletes a task by its ID.
 */
export const deleteHomeTask = async (id: string): Promise<void> => {
  await api.delete(`/home/tasks/${id}`);
};


// --- Appliance Functions ---

/**
 * (Read) Fetches all registered appliances.
 */
export const fetchAppliances = async (): Promise<Appliance[]> => {
  const response = await api.get<Appliance[]>("/home/appliances");
  return response.data;
};