import api from "./index";
import { Chore, Expense } from "../types/sharedLiving";

/**
 * Fetches all chores for the shared living space.
 */
export const fetchChores = async (): Promise<Chore[]> => {
  const response = await api.get<Chore[]>("/shared-living/chores");
  return response.data;
};

/**
 * Fetches all expenses for the shared living space.
 */
export const fetchExpenses = async (): Promise<Expense[]> => {
  const response = await api.get<Expense[]>("/shared-living/expenses");
  return response.data;
};

/**
 * Adds a new expense.
 * The input type is Omit<Expense, 'id'> because the ID is generated by the backend.
 */
export const addExpense = async (newExpense: Omit<Expense, 'id'>): Promise<Expense> => {
  const response = await api.post<Expense>("/shared-living/expenses", newExpense);
  return response.data;
};